---
- hosts: target1
  become: true
  tasks:
    - name: Add several users
      user:
        name: "{{ item }}"
        state: present
        create_home: true
      with_items:
        - alice
        - bob
