version: "3.4"

services:
  mealie:
    image: hkotel/mealie
    container_name: mealie
    restart: always
    ports:
      - 9090:80
    environment:
      DB_ENGINE: postgres # Optional: 'sqlite', 'postgres'
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_SERVER: 192.168.56.12
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
