---
all:
  vars:
    ansible_user: vagrant
    
  hosts:
    host1:
      ansible_host: 192.168.56.11
      ansible_ssh_private_key_file: /vagrant/.vagrant/machines/target1/virtualbox/private_key
    host2:
      ansible_host: 192.168.56.12
      ansible_ssh_private_key_file: /vagrant/.vagrant/machines/target2/virtualbox/private_key
 